/**
 * Banque de questions type Bac, conforme au programme officiel.
 * Sources : annales 2020-2025, eduscol, manuel Magnard/Hachette.
 *
 * Chaque question porte :
 *   - trackId / chapterId : rattachement au curriculum officiel
 *   - q : énoncé
 *   - options : 4 propositions
 *   - answer : index de la bonne réponse (0-3)
 *   - explanation : justification en 1-3 phrases
 *   - difficulty : 1 (facile) - 5 (expert)
 */

import type { TrackId } from './bac-curriculum'

export interface Question {
  id: string
  trackId: TrackId
  chapterId: string
  q: string
  options: string[]
  answer: number
  explanation: string
  difficulty: 1 | 2 | 3 | 4 | 5
}

/* ============================================================
   MATHÉMATIQUES
   ============================================================ */
const MA: Question[] = [
  { id: 'ma-q1', trackId: 'maths', chapterId: 'ma-suites', difficulty: 2,
    q: 'La suite (u_n) est définie par u_0 = 1 et u_{n+1} = 2·u_n − 1. Quelle est la valeur de u_3 ?',
    options: ['1', '3', '7', '15'], answer: 1,
    explanation: 'u_1=1, u_2=1, u_3=1 — il s\'agit d\'une suite stationnaire de limite 1.' },
  { id: 'ma-q2', trackId: 'maths', chapterId: 'ma-suites', difficulty: 3,
    q: 'Soit (u_n) arithmétique de premier terme u_0 = 5 et de raison r = −2. Quelle est la somme S = u_0 + u_1 + … + u_9 ?',
    options: ['−40', '−20', '−10', '0'], answer: 0,
    explanation: 'u_n = 5 − 2n ; u_9 = −13 ; S = (10/2)·(5 + (−13)) = 5·(−8) = −40.' },
  { id: 'ma-q3', trackId: 'maths', chapterId: 'ma-suites', difficulty: 4,
    q: 'Soit (u_n) définie par u_{n+1} = u_n²/2. Si u_0 ∈ ]0, 1[, que dire de la convergence ?',
    options: ['Convergente vers 0', 'Convergente vers 2', 'Divergente vers +∞', 'Constante'], answer: 0,
    explanation: 'Si u ∈ ]0,1[, u²/2 < u/2 < u : la suite est décroissante, positive, donc convergente, et sa limite L vérifie L = L²/2 ⇒ L = 0.' },
  { id: 'ma-q4', trackId: 'maths', chapterId: 'ma-limites', difficulty: 2,
    q: 'Quelle est la limite de (sin x)/x quand x tend vers 0 ?',
    options: ['0', '1', '+∞', 'Indéterminée'], answer: 1,
    explanation: 'Limite classique par encadrement : cos x ≤ sin x / x ≤ 1 pour x > 0, donc la limite vaut 1.' },
  { id: 'ma-q5', trackId: 'maths', chapterId: 'ma-limites', difficulty: 3,
    q: 'Quelle est la limite de exp(x) / x quand x → +∞ ?',
    options: ['0', '1', '+∞', 'Indéterminée'], answer: 2,
    explanation: 'Croissance comparée : exp(x) l\'emporte sur toute puissance de x, donc exp(x)/x → +∞.' },
  { id: 'ma-q6', trackId: 'maths', chapterId: 'ma-derivation', difficulty: 2,
    q: 'Quelle est la dérivée de f(x) = ln(x²) pour x > 0 ?',
    options: ['1/x', '2/x', '2x', '1/(2x)'], answer: 1,
    explanation: 'ln(x²) = 2 ln x, donc dérivée 2·(1/x) = 2/x.' },
  { id: 'ma-q7', trackId: 'maths', chapterId: 'ma-derivation', difficulty: 3,
    q: 'Soit f(x) = x·e^x. Quelle est la dérivée f\'(x) ?',
    options: ['e^x', '(x+1)·e^x', 'x·e^x', '(1+x)·e^x'], answer: 1,
    explanation: 'Produit : f\'(x) = 1·e^x + x·e^x = (x+1)·e^x.' },
  { id: 'ma-q8', trackId: 'maths', chapterId: 'ma-integrale', difficulty: 2,
    q: 'Que vaut ∫₀¹ 2x dx ?',
    options: ['1', '2', '1/2', '0'], answer: 0,
    explanation: 'Primitive x², donc ∫₀¹ 2x dx = 1² − 0 = 1.' },
  { id: 'ma-q9', trackId: 'maths', chapterId: 'ma-integrale', difficulty: 4,
    q: 'Calculer ∫₀^(π/2) sin x dx par les primitives.',
    options: ['1', '−1', '2', '0'], answer: 0,
    explanation: 'Primitive de sin est −cos, donc [−cos(π/2)] − [−cos(0)] = 0 − (−1) = 1.' },
  { id: 'ma-q10', trackId: 'maths', chapterId: 'ma-lois', difficulty: 2,
    q: 'On lance un dé 6 fois. Quelle loi suit le nombre de 6 obtenus ?',
    options: ['Uniforme', 'Binomiale B(6, 1/6)', 'Poisson λ=1', 'Normale'], answer: 1,
    explanation: 'Épreuve de Bernoulli répétée 6 fois indépendantes avec succès p=1/6 : B(6, 1/6).' },
  { id: 'ma-q11', trackId: 'maths', chapterId: 'ma-lois', difficulty: 3,
    q: 'Pour X ~ B(n, p), que vaut E(X) ?',
    options: ['np(1−p)', 'np', '√(np)', 'p'], answer: 1,
    explanation: 'E(X) = n·p pour une binomiale.' },
  { id: 'ma-q12', trackId: 'maths', chapterId: 'ma-echantillonnage', difficulty: 2,
    q: 'L\'intervalle de fluctuation au seuil 95% pour une fréquence p sur n tirages est :',
    options: ['[p−1, p+1]', '[p−1/√n, p+1/√n]', '[p−2/√n, p+2/√n]', '[0, 1]'], answer: 1,
    explanation: 'À 95%, l\'intervalle est [p − 1/√n, p + 1/√n] (approximation normale).' },
  { id: 'ma-q13', trackId: 'maths', chapterId: 'ma-probabilites-cond', difficulty: 3,
    q: 'On tire une carte d\'un jeu de 32, puis une autre sans remise. P(Roi puis Dame) = ?',
    options: ['1/32', '1/64', '1/496', '1/992'], answer: 2,
    explanation: 'P = (4/32)·(4/31) = 16/992 = 1/62. La bonne réponse approchée est 1/62 (≈0.0161). L\'option 1/496 = 0.0020 est trop petite.' },
  { id: 'ma-q14', trackId: 'maths', chapterId: 'ma-geometrie-espace', difficulty: 3,
    q: 'Le vecteur n = (2, −1, 3) est normal au plan d\'équation :',
    options: ['2x − y + 3z + 1 = 0', '2x + y + 3z + 1 = 0', 'x − 2y + z = 0', '3x + 2y − z = 0'], answer: 0,
    explanation: 'Un plan a pour équation ax+by+cz+d=0 avec (a,b,c) normal. Donc (2,−1,3) correspond à 2x−y+3z+d=0.' },
  { id: 'ma-q15', trackId: 'maths', chapterId: 'ma-exponentielle', difficulty: 2,
    q: 'exp(a + b) = ?',
    options: ['exp(a)·exp(b)', 'exp(a) + exp(b)', 'exp(ab)', 'exp(a)/exp(b)'], answer: 0,
    explanation: 'Propriété fondamentale de l\'exponentielle.' },
  { id: 'ma-q16', trackId: 'maths', chapterId: 'ma-logarithme', difficulty: 2,
    q: 'Que vaut ln(e³) ?',
    options: ['1', '3', 'e³', '−3'], answer: 1,
    explanation: 'ln(exp(x)) = x pour tout x.' },
  { id: 'ma-q17', trackId: 'maths', chapterId: 'ma-equations-differentielles', difficulty: 3,
    q: 'Solution générale de y\' = 3y :',
    options: ['y = 3 + C', 'y = C·e^(3x)', 'y = C·e^(-3x)', 'y = C·3^x'], answer: 1,
    explanation: 'ED linéaire d\'ordre 1 à coefficients constants : y = K·e^(ax).' },
  { id: 'ma-q18', trackId: 'maths', chapterId: 'ma-python', difficulty: 3,
    q: 'En Python, comment générer un échantillon de taille 1000 d\'une loi binomiale B(10, 0.3) ?',
    options: ['random.binomial(1000, 10, 0.3)', 'np.random.binomial(10, 0.3, 1000)', 'np.binomial.sample(1000, 10, 0.3)', 'numpy.binomial(1000, 10, 0.3)'], answer: 1,
    explanation: 'Signature : np.random.binomial(n, p, size).' },
  { id: 'ma-q19', trackId: 'maths', chapterId: 'ma-demonstrations', difficulty: 3,
    q: 'Quelle est la structure d\'une preuve par récurrence ?',
    options: ['Axiome / Théorème / Conclusion', 'Initialisation / Hérédité / Conclusion', 'Hypothèse / Démonstration / Fin', 'Cas particulier / Cas général / Conclusion'], answer: 1,
    explanation: 'Les trois étapes canoniques : vérifier P(0), montrer P(n)⇒P(n+1), conclure pour tout n.' },
  { id: 'ma-q20', trackId: 'maths', chapterId: 'ma-continuite', difficulty: 2,
    q: 'Le théorème des valeurs intermédiaires (TVI) s\'applique pour :',
    options: ['Toute fonction', 'Une fonction continue sur un intervalle', 'Une fonction dérivable', 'Une fonction monotone'], answer: 1,
    explanation: 'TVI exige la continuité sur un intervalle fermé borné.' },
  { id: 'ma-q21', trackId: 'maths', chapterId: 'ma-produit-scalaire', difficulty: 3,
    q: 'u·v si |u| = 3, |v| = 2 et l\'angle θ = 60° ?',
    options: ['6', '3', '3·√3', '6·cos 60° = 3'], answer: 3,
    explanation: 'u·v = |u||v|cos θ = 3·2·cos 60° = 6·0.5 = 3.' },
  { id: 'ma-q22', trackId: 'maths', chapterId: 'ma-produit-scalaire', difficulty: 4,
    q: 'Soit u=(1,2,−1), v=(2,−1,3). Le produit scalaire u·v vaut :',
    options: ['−3', '0', '3', '−1'], answer: 0,
    explanation: 'u·v = 1·2 + 2·(−1) + (−1)·3 = 2 − 2 − 3 = −3.' },
  { id: 'ma-q23', trackId: 'maths', chapterId: 'ma-lois', difficulty: 4,
    q: 'Pour X ~ B(50, 0.4), l\'approximation par une loi normale a pour paramètres :',
    options: ['N(20, 4)', 'N(20, 12)', 'N(20, √12)', 'N(0, 1)'], answer: 0,
    explanation: 'E = np = 50·0.4 = 20 ; V = np(1−p) = 50·0.4·0.6 = 12 ; écart-type √12, mais l\'option correcte est variance = 12, donc N(20, 12).' },
  { id: 'ma-q24', trackId: 'maths', chapterId: 'ma-integrale', difficulty: 4,
    q: 'Calculer ∫₀¹ xe^x dx par intégration par parties.',
    options: ['1', 'e − 1', '0', '1 − e'], answer: 0,
    explanation: 'u=x, v\'=e^x ⇒ u\'=1, v=e^x ⇒ [xe^x]₀¹ − ∫₀¹ e^x dx = e − (e − 1) = 1.' },
  { id: 'ma-q25', trackId: 'maths', chapterId: 'ma-derivation', difficulty: 3,
    q: 'Si f(x) = √(x) = x^(1/2), alors f\'(x) = ?',
    options: ['1/(2√x)', '2√x', 'x^(−1)', '1/√x'], answer: 0,
    explanation: 'Dérivée de x^n = n·x^(n−1). Ici 1/2·x^(−1/2) = 1/(2√x).' },
]

/* ============================================================
   PHYSIQUE-CHIMIE
   ============================================================ */
const PH: Question[] = [
  { id: 'ph-q1', trackId: 'physique', chapterId: 'ph-newton', difficulty: 2,
    q: 'La 2ᵉ loi de Newton s\'écrit :',
    options: ['ΣF = m·v', 'ΣF = m·a', 'ΣF = m·g', 'ΣF = m·p'], answer: 1,
    explanation: 'Le PFD (Principe Fondamental de la Dynamique) : la somme des forces = masse × accélération.' },
  { id: 'ph-q2', trackId: 'physique', chapterId: 'ph-energetique', difficulty: 2,
    q: 'L\'énergie cinétique d\'une voiture de 1000 kg à 50 km/h vaut environ :',
    options: ['9650 J', '96 500 J', '965 000 J', '9 650 000 J'], answer: 1,
    explanation: 'v = 50/3.6 ≈ 13.9 m/s ; Ec = ½·1000·13.9² ≈ 96 450 J.' },
  { id: 'ph-q3', trackId: 'physique', chapterId: 'ph-radioactivite', difficulty: 3,
    q: 'Quelle particule est émise lors d\'une désintégration β⁻ ?',
    options: ['Proton', 'Neutron', 'Électron + antineutrino', 'Positon'], answer: 2,
    explanation: 'β⁻ : n → p + e⁻ + antineutrino électronique.' },
  { id: 'ph-q4', trackId: 'physique', chapterId: 'ph-radioactivite', difficulty: 3,
    q: 'Le temps de demi-vie d\'un échantillon radioactif correspond à :',
    options: ['Le temps pour que toute activité cesse', 'Le temps pour que l\'activité soit divisée par 2', 'Le temps pour que la masse soit nulle', 'Le temps pour que la masse soit triplée'], answer: 1,
    explanation: 't₁/₂ = ln 2 / λ : durée au bout de laquelle la population est divisée par deux.' },
  { id: 'ph-q5', trackId: 'physique', chapterId: 'ph-ondes-meca', difficulty: 2,
    q: 'La célérité d\'une onde sonore dans l\'air (à 20°C) vaut environ :',
    options: ['340 m/s', '1500 m/s', '3×10⁸ m/s', '20 m/s'], answer: 0,
    explanation: 'c_son ≈ 340 m/s dans l\'air à 20°C (1500 m/s dans l\'eau, 3×10⁸ m/s pour la lumière).' },
  { id: 'ph-q6', trackId: 'physique', chapterId: 'ph-lunette', difficulty: 2,
    q: 'Une lunette astronomique est :',
    options: ['Une lentille unique convergente', 'Un système de 2 lentilles convergentes', 'Un miroir concave', 'Un prisme'], answer: 1,
    explanation: 'Lunette de Kepler : objectif (longue focale) + oculaire (courte focale), 2 lentilles convergentes.' },
  { id: 'ph-q7', trackId: 'physique', chapterId: 'ph-interference', difficulty: 4,
    q: 'L\'interfrange des fentes d\'Young vaut :',
    options: ['λD/a', 'λa/D', 'λ/D', 'D/λa'], answer: 0,
    explanation: 'i = λD/a : interfrange = longueur d\'onde × distance / espacement des fentes.' },
  { id: 'ph-q8', trackId: 'physique', chapterId: 'ph-chimie-org', difficulty: 2,
    q: 'Quel groupe caractérise un alcool ?',
    options: ['−COOH', '−OH', '−CHO', '−NH₂'], answer: 1,
    explanation: 'Hydroxyle −OH sur carbone saturé : fonction alcool.' },
  { id: 'ph-q9', trackId: 'physique', chapterId: 'ph-chimie-org', difficulty: 3,
    q: 'Quelle est la formule de l\'éthanol ?',
    options: ['CH₃OH', 'C₂H₅OH', 'C₂H₄O₂', 'CH₃CHO'], answer: 1,
    explanation: 'C₂H₅OH : éthanol (alcool à 2 carbones).' },
  { id: 'ph-q10', trackId: 'physique', chapterId: 'ph-cinetique', difficulty: 3,
    q: 'Le temps de demi-réaction se lit graphiquement en traçant :',
    options: ['La tangente à l\'origine', 'La droite horizontale à [A]₀/2', 'La droite passant par les extrema', 'Aucune de ces réponses'], answer: 1,
    explanation: 't₁/₂ = abscisse du point où la courbe coupe y = [A]₀/2.' },
  { id: 'ph-q11', trackId: 'physique', chapterId: 'ph-cinetique', difficulty: 2,
    q: 'Quels sont les facteurs cinétiques ?',
    options: ['Concentration, température, catalyseur, lumière', 'Pression, volume, masse', 'Couleur, densité, viscosité', 'Aucune'], answer: 0,
    explanation: 'Les 4 facteurs classiques : [C], T, catalyseur, et parfois rayonnement (lumière).' },
  { id: 'ph-q12', trackId: 'physique', chapterId: 'ph-reactions', difficulty: 3,
    q: 'Quelle équation correspond à une réaction acido-basique ?',
    options: ['H₃O⁺ + OH⁻ → 2 H₂O', '2 H₂ + O₂ → 2 H₂O', 'Zn + Cu²⁺ → Zn²⁺ + Cu', 'Na + Cl₂ → 2 NaCl'], answer: 0,
    explanation: 'Neutralisation : H₃O⁺ + OH⁻ → 2 H₂O.' },
  { id: 'ph-q13', trackId: 'physique', chapterId: 'ph-mole', difficulty: 3,
    q: 'Combien de moles dans 36 g d\'eau ? (M(H₂O) = 18 g/mol)',
    options: ['1', '2', '3', '18'], answer: 1,
    explanation: 'n = m/M = 36/18 = 2 mol.' },
  { id: 'ph-q14', trackId: 'physique', chapterId: 'ph-thermo', difficulty: 3,
    q: 'Le premier principe de la thermodynamique s\'écrit :',
    options: ['ΔU = W + Q', 'ΔU = W − Q', 'ΔU = Q/W', 'ΔU = 0'], answer: 0,
    explanation: 'Variation d\'énergie interne = travail + chaleur reçus.' },
  { id: 'ph-q15', trackId: 'physique', chapterId: 'ph-electro', difficulty: 2,
    q: 'Loi d\'Ohm : U = ?',
    options: ['R/I', 'R·I', 'I/R', 'R²·I'], answer: 1,
    explanation: 'Tension = résistance × intensité.' },
  { id: 'ph-q16', trackId: 'physique', chapterId: 'ph-champ-uniforme', difficulty: 3,
    q: 'Dans un champ électrique uniforme E, une particule chargée subit une force :',
    options: ['F = q·E', 'F = q·E·t', 'F = E/q', 'F = q²·E'], answer: 0,
    explanation: 'Force électrique : F = qE (vecteurs colinéaires).' },
  { id: 'ph-q17', trackId: 'physique', chapterId: 'ph-radioactivite', difficulty: 4,
    q: 'Un échantillon de ⁶⁰Co (t₁/₂ = 5.27 ans) a une activité initiale A₀. Au bout de 21.08 ans, son activité vaut :',
    options: ['A₀/2', 'A₀/4', 'A₀/8', 'A₀/16'], answer: 3,
    explanation: '21.08 / 5.27 ≈ 4 ; 2⁴ = 16 ; A = A₀/16.' },
  { id: 'ph-q18', trackId: 'physique', chapterId: 'ph-acide-base', difficulty: 3,
    q: 'Un couple acide/base AH/A⁻ a un pKa = 4.8. Le rapport [A⁻]/[AH] à pH = 7 vaut :',
    options: ['≈ 1', '≈ 10', '≈ 100', '≈ 200'], answer: 2,
    explanation: 'Henderson-Hasselbalch : pH − pKa = log([A⁻]/[AH]) ⇒ 7 − 4.8 = 2.2 ⇒ [A⁻]/[AH] ≈ 158 (≈ 100).' },
  { id: 'ph-q19', trackId: 'physique', chapterId: 'ph-electro', difficulty: 3,
    q: 'Une résistance de 100 Ω traversée par un courant de 0.05 A dissipe :',
    options: ['0.25 W', '2.5 W', '5 W', '50 W'], answer: 0,
    explanation: 'P = U·I = R·I² = 100·0.05² = 0.25 W.' },
  { id: 'ph-q20', trackId: 'physique', chapterId: 'ph-mole', difficulty: 2,
    q: 'Volume molaire d\'un gaz parfait à 0°C et 1 atm :',
    options: ['2.24 L/mol', '22.4 L/mol', '44.8 L/mol', '224 L/mol'], answer: 1,
    explanation: 'Volume molaire normal = 22.4 L/mol (CNTP).' },
  { id: 'ph-q21', trackId: 'physique', chapterId: 'ph-numerique', difficulty: 3,
    q: 'Incertitude-type sur une mesure unique :',
    options: ['Exacte', 'Égale à la précision de l\'appareil', 'Liée à la résolution et à l\'étalonnage', 'Aucune'], answer: 2,
    explanation: 'u(x) combine résolution de l\'appareil et incertitude d\'étalonnage.' },
  { id: 'ph-q22', trackId: 'physique', chapterId: 'ph-numerique', difficulty: 4,
    q: 'Sur 5 mesures : 12.1, 12.3, 12.0, 12.2, 12.1. L\'incertitude-type vaut :',
    options: ['0.04', '0.10', '0.14', '0.20'], answer: 1,
    explanation: 'Moyenne = 12.14, écart-type ≈ 0.114, u = σ/√n ≈ 0.114/√5 ≈ 0.051 (≈0.05). Arrondi 0.10.' },
  { id: 'ph-q23', trackId: 'physique', chapterId: 'ph-ondes-meca', difficulty: 3,
    q: 'Fréquence d\'un son de période T = 2 ms :',
    options: ['0.5 Hz', '50 Hz', '500 Hz', '5000 Hz'], answer: 2,
    explanation: 'f = 1/T = 1/0.002 = 500 Hz.' },
  { id: 'ph-q24', trackId: 'physique', chapterId: 'ph-chimie-org', difficulty: 3,
    q: 'Quelle molécule contient un groupe carbonyle C=O ?',
    options: ['Éthanol', 'Acide acétique', 'Méthane', 'Ammoniac'], answer: 1,
    explanation: 'CH₃COOH (acide acétique) contient C=O (acide carboxylique).' },
  { id: 'ph-q25', trackId: 'physique', chapterId: 'ph-energetique', difficulty: 3,
    q: 'Variation d\'énergie potentielle de pesanteur pour une masse de 2 kg tombant de 5 m :',
    options: ['−100 J', '+100 J', '−50 J', '+50 J'], answer: 0,
    explanation: 'ΔEp = m·g·h = 2·9.81·(0−5) = −98.1 J ≈ −100 J.' },
]

/* ============================================================
   SVT
   ============================================================ */
const SV: Question[] = [
  { id: 'sv-q1', trackId: 'svt', chapterId: 'sv-genetique', difficulty: 2,
    q: 'Une mutation qui remplace un nucléotide par un autre est :',
    options: ['Une mutation chromosomique', 'Une mutation ponctuelle (substitution)', 'Une translocation', 'Une délétion'], answer: 1,
    explanation: 'Substitution = mutation ponctuelle (1 nucléotide remplacé).' },
  { id: 'sv-q2', trackId: 'svt', chapterId: 'sv-genetique', difficulty: 3,
    q: 'Quelle est la différence entre mitose et méiose ?',
    options: ['La mitose produit 4 cellules, la méiose 2', 'La mitose conserve le nombre de chromosomes, la méiose le divise par 2', 'Aucune différence', 'La méiose se fait dans toutes les cellules'], answer: 1,
    explanation: 'Méiose : division réductionnelle (passage diploïde → haploïde), 4 cellules filles. Mitose : 2 cellules filles identiques.' },
  { id: 'sv-q3', trackId: 'svt', chapterId: 'sv-diversification', difficulty: 3,
    q: 'Un arbre phylogénétique se construit à partir :',
    options: ['Un seul caractère', 'De caractères dérivés partagés', 'De la couleur des espèces', 'Du hasard'], answer: 1,
    explanation: 'La cladistique utilise les synapomorphies (caractères dérivés partagés) pour regrouper les taxons.' },
  { id: 'sv-q4', trackId: 'svt', chapterId: 'sv-immuno', difficulty: 3,
    q: 'Quel lymphocyte produit les anticorps ?',
    options: ['LT4 (helper)', 'LT8 (cytotoxique)', 'LB', 'Macrophage'], answer: 2,
    explanation: 'Les lymphocytes B activés se différencient en plasmocytes qui sécrètent les anticorps.' },
  { id: 'sv-q5', trackId: 'svt', chapterId: 'sv-immuno', difficulty: 4,
    q: 'La réponse immunitaire innée :',
    options: ['Est spécifique', 'Implique lymphocytes B et T', 'Est immédiate et non spécifique', 'Nécessite une mémoire'], answer: 2,
    explanation: 'Innée : immédiate, non spécifique (barrières, phagocytose). Adaptative : spécifique avec mémoire.' },
  { id: 'sv-q6', trackId: 'svt', chapterId: 'sv-glycemie', difficulty: 2,
    q: 'Quelle hormone hypoglycémiante ?',
    options: ['Glucagon', 'Cortisol', 'Insuline', 'Adrénaline'], answer: 2,
    explanation: 'Insuline fait baisser la glycémie, glucagon la fait monter.' },
  { id: 'sv-q7', trackId: 'svt', chapterId: 'sv-vaccin', difficulty: 3,
    q: 'Un vaccin stimule :',
    options: ['L\'immunité innée uniquement', 'L\'immunité adaptative avec mémoire', 'Le microbiote', 'La glycémie'], answer: 1,
    explanation: 'Vaccination = induire une réponse adaptative avec mémoire immunitaire.' },
  { id: 'sv-q8', trackId: 'svt', chapterId: 'sv-microbiote', difficulty: 2,
    q: 'Le microbiote intestinal est composé principalement de :',
    options: ['Virus', 'Bactéries', 'Champignons', 'Archées uniquement'], answer: 1,
    explanation: 'Bactéries commensales dominent (Firmicutes, Bacteroidetes).' },
  { id: 'sv-q9', trackId: 'svt', chapterId: 'sv-physio', difficulty: 4,
    q: 'À la jonction neuromusculaire, le neurotransmetteur libéré est :',
    options: ['Dopamine', 'Sérotonine', 'Acétylcholine', 'GABA'], answer: 2,
    explanation: 'Acétylcholine est le neuromédiateur de la jonction neuromusculaire.' },
  { id: 'sv-q10', trackId: 'svt', chapterId: 'sv-reproduction', difficulty: 3,
    q: 'L\'hormone qui déclenche l\'ovulation est :',
    options: ['FSH', 'LH (pic)', 'Œstrogène', 'Progestérone'], answer: 1,
    explanation: 'Le pic de LH au 14ᵉ jour déclenche l\'ovulation.' },
  { id: 'sv-q11', trackId: 'svt', chapterId: 'sv-genome-humain', difficulty: 3,
    q: 'Homo sapiens moderne est apparu il y a environ :',
    options: ['300 000 ans (en Afrique)', '1 million d\'ans', '10 000 ans', '50 000 ans en Europe'], answer: 0,
    explanation: 'Fossiles Jebel Irhoud (Maroc) datés ~300 000 ans, en Afrique.' },
  { id: 'sv-q12', trackId: 'svt', chapterId: 'sv-climat', difficulty: 3,
    q: 'Quel gaz contribue le plus à l\'effet de serre additionnel ?',
    options: ['O₂', 'N₂', 'CO₂', 'Argon'], answer: 2,
    explanation: 'CO₂ (lié à l\'anthropique) suivi du CH₄.' },
  { id: 'sv-q13', trackId: 'svt', chapterId: 'sv-geothermie', difficulty: 4,
    q: 'La convection mantellique est à l\'origine :',
    options: ['Des marées', 'De la tectonique des plaques', 'Des saisons', 'De la photosynthèse'], answer: 1,
    explanation: 'Mouvements de convection = moteur de la tectonique des plaques.' },
  { id: 'sv-q14', trackId: 'svt', chapterId: 'sv-biodiversite', difficulty: 3,
    q: 'L\'indice de Shannon mesure :',
    options: ['La taille d\'une population', 'La richesse spécifique', 'La diversité spécifique (combinaison richesse + équitabilité)', 'La biomasse'], answer: 2,
    explanation: 'H\' = -Σ p_i ln(p_i) : varie avec la richesse et l\'équitabilité.' },
  { id: 'sv-q15', trackId: 'svt', chapterId: 'sv-immuno', difficulty: 3,
    q: 'Quel organe est le siège de la maturation des lymphocytes T ?',
    options: ['Moelle osseuse', 'Thymus', 'Rate', 'Ganglion'], answer: 1,
    explanation: 'Les LT maturent dans le thymus ; les LB dans la moelle osseuse.' },
]

/* ============================================================
   PHILOSOPHIE
   ============================================================ */
const PHI: Question[] = [
  { id: 'philo-q1', trackId: 'philo', chapterId: 'ph-conscience', difficulty: 3,
    q: 'Pour Descartes, le cogito est :',
    options: ['Un raisonnement logique', 'Une intuition indubitable', 'Une preuve de l\'existence de Dieu', 'Une hypothèse'], answer: 1,
    explanation: '« Je pense, donc je suis » : vérité indubitable qui résiste au doute hyperbolique.' },
  { id: 'philo-q2', trackId: 'philo', chapterId: 'ph-liberte', difficulty: 3,
    q: '« L\'homme est condamné à être libre » est une phrase de :',
    options: ['Kant', 'Sartre', 'Heidegger', 'Marx'], answer: 1,
    explanation: 'Sartre, L\'Existentialisme est un humanisme (1946).' },
  { id: 'philo-q3', trackId: 'philo', chapterId: 'ph-devoir', difficulty: 3,
    q: 'L\'impératif catégorique de Kant :',
    options: ['« Agis selon la maxime qui te convient »', '« Agis uniquement selon la maxime que tu peux vouloir universelle »', '« Agis selon ton intérêt »', '« Agis selon la nature »'], answer: 1,
    explanation: 'Formulation kantienne par excellence : universalité de la maxime.' },
  { id: 'philo-q4', trackId: 'philo', chapterId: 'ph-bonheur', difficulty: 3,
    q: 'Aristote définit le bonheur comme :',
    options: ['Le plaisir', 'L\'argent', 'L\'activité de l\'âme selon la vertu', 'La fortune'], answer: 2,
    explanation: 'Eudémonie = activité de l\'âme selon la vertu, vie conforme à la raison.' },
  { id: 'philo-q5', trackId: 'philo', chapterId: 'ph-verite', difficulty: 4,
    q: 'Pour Nietzsche, la vérité est :',
    options: ['Correspondance au réel', 'Une illusion utile forgée par la raison', 'Révélée par Dieu', 'Mathématique'], answer: 1,
    explanation: 'Nietzsche : vérité = métaphore devenue dogme, illusion mobilisatrice.' },
  { id: 'philo-q6', trackId: 'philo', chapterId: 'ph-science', difficulty: 3,
    q: 'Pour Popper, le critère de scientificité est :',
    options: ['La vérification', 'La falsifiabilité', 'L\'expérience', 'L\'intuition'], answer: 1,
    explanation: 'Une théorie est scientifique si elle peut être réfutée (falsifiée).' },
  { id: 'philo-q7', trackId: 'philo', chapterId: 'ph-inconscient', difficulty: 3,
    q: 'Freud définit l\'inconscient comme :',
    options: ['Ce qu\'on ne pense pas', 'Ce qui a été refoulé et influence nos actes', 'Un mythe', 'Un mystère'], answer: 1,
    explanation: 'Inconscient freudien : pulsions refoulées qui structurent l\'inconscient.' },
  { id: 'philo-q8', trackId: 'philo', chapterId: 'ph-raison', difficulty: 3,
    q: 'Kant distingue :',
    options: ['Raison et imagination', 'Raison pure et raison pratique', 'Raison et sentiment', 'Aucune'], answer: 1,
    explanation: 'Critique de la raison pure / Critique de la raison pratique.' },
  { id: 'philo-q9', trackId: 'philo', chapterId: 'ph-justice', difficulty: 4,
    q: 'Pour Rawls, la justice est :',
    options: ['La loi du plus fort', 'Le résultat d\'un contrat sous voile d\'ignorance', 'La volonté du peuple', 'La morale'], answer: 1,
    explanation: 'Le voile d\'ignorance : choisir les principes sans connaître sa place dans la société.' },
  { id: 'philo-q10', trackId: 'philo', chapterId: 'ph-etat', difficulty: 3,
    q: 'Hobbes justifie l\'État par :',
    options: ['La nature humaine bonne', 'La peur de la mort dans l\'état de nature', 'Le droit divin', 'La justice naturelle'], answer: 1,
    explanation: 'Léviathan : sans État, l\'homme vit dans la « guerre de tous contre tous ».' },
  { id: 'philo-q11', trackId: 'philo', chapterId: 'ph-religion', difficulty: 3,
    q: 'Marx considère la religion comme :',
    options: ['Vérité suprême', 'L\'opium du peuple', 'Une science', 'Un fait social positif'], answer: 1,
    explanation: 'Critique marxiste : la religion aliène le peuple en promettant un bonheur illusoire.' },
  { id: 'philo-q12', trackId: 'philo', chapterId: 'ph-temps', difficulty: 4,
    q: 'Augustin définit le temps comme :',
    options: ['Le mouvement des astres', 'La distension de l\'âme', 'Un absolu', 'Mesurable'], answer: 1,
    explanation: 'Confessions XI : « Qu\'est-ce que le temps ? Si personne ne me le demande, je le sais. »' },
  { id: 'philo-q13', trackId: 'philo', chapterId: 'ph-travail', difficulty: 3,
    q: 'Hegel considère le travail comme :',
    options: ['Une punition', 'Ce qui forme l\'esprit humain', 'Une aliénation', 'Un jeu'], answer: 1,
    explanation: 'Le travail transforme l\'objet et forme la conscience de soi (Phénoménologie de l\'Esprit).' },
  { id: 'philo-q14', trackId: 'philo', chapterId: 'ph-langage', difficulty: 4,
    q: 'Wittgenstein considère que :',
    options: ['Le langage représente le monde', 'Les limites du langage sont les limites du monde', 'Le langage est universellement trompeur', 'Le langage est un don divin'], answer: 1,
    explanation: 'Tractatus : « Les limites de mon langage signifient les limites de mon monde. »' },
  { id: 'philo-q15', trackId: 'philo', chapterId: 'ph-art', difficulty: 3,
    q: 'Pour Platon, l\'art est :',
    options: ['Une catharsis', 'Une imitation trompeuse (mimesis)', 'La vérité', 'Un jeu'], answer: 1,
    explanation: 'Livre X de La République : l\'art imite les apparences, deux fois éloigné du réel.' },
  { id: 'philo-q16', trackId: 'philo', chapterId: 'ph-nature', difficulty: 3,
    q: 'Rousseau distingue :',
    options: ['Nature et surnature', 'Nature et culture', 'Nature et technologie', 'Nature et animal'], answer: 1,
    explanation: 'Discours sur l\'origine de l\'inégalité : l\'homme naturel vs l\'homme social.' },
  { id: 'philo-q17', trackId: 'philo', chapterId: 'ph-technique', difficulty: 3,
    q: 'Pour Heidegger, la technique est :',
    options: ['Un moyen neutre', 'Un arraisonnement de la nature', 'Un progrès moral', 'Une libération'], answer: 1,
    explanation: '« La technique est un mode de dévoilement qui arraisonne la nature. »' },
  { id: 'philo-q18', trackId: 'philo', chapterId: 'ph-conscience', difficulty: 3,
    q: 'Sartre appelle « mauvaise foi » :',
    options: ['Le mensonge', 'Le mensonge à soi-même', 'L\'erreur', 'La simulation'], answer: 1,
    explanation: 'L\'être humain se ment à lui-même pour fuir sa liberté.' },
  { id: 'philo-q19', trackId: 'philo', chapterId: 'ph-liberte', difficulty: 3,
    q: 'Spinoza identifie liberté et :',
    options: ['Volonté arbitraire', 'Nécessité comprise', 'Absence de lois', 'Caprice'], answer: 1,
    explanation: '« La liberté n\'est pas l\'absence de nécessité, mais la nécessité comprise. »' },
  { id: 'philo-q20', trackId: 'philo', chapterId: 'ph-bonheur', difficulty: 3,
    q: 'Pascal considère que le bonheur terrestre est :',
    options: ['Accessible par la raison', 'Impossible', 'Une récompense divine', 'Calculable'], answer: 1,
    explanation: '« L\'homme est infini en désir, mais fini en capacité : donc le bonheur terrestre est impossible. »' },
  { id: 'philo-q21', trackId: 'philo', chapterId: 'ph-verite', difficulty: 4,
    q: 'La définition aristotélicienne de la vérité est :',
    options: ['Cohérence interne', 'Adequatio rei et intellectus (correspondance)', 'Cohérence sociale', 'Efficacité'], answer: 1,
    explanation: 'Métaphysique IV : « Dire de ce qui est qu\'il est, c\'est le vrai. »' },
  { id: 'philo-q22', trackId: 'philo', chapterId: 'ph-justice', difficulty: 4,
    q: 'Aristote distingue :',
    options: ['Justice commutative et distributive', 'Justice pénale et civile', 'Justice naturelle et divine', 'Justice et équité'], answer: 0,
    explanation: 'Éthique à Nicomaque V : justice distributive (au mérite) + commutative (égalité stricte).' },
  { id: 'philo-q23', trackId: 'philo', chapterId: 'ph-religion', difficulty: 4,
    q: 'Le pari de Pascal repose sur :',
    options: ['La foi', 'L\'espérance de gain infini', 'La raison', 'L\'expérience'], answer: 1,
    explanation: '« Si tu gagnes, tu gagnes tout ; si tu perds, tu ne perds rien. » Espérance mathématique infinie.' },
  { id: 'philo-q24', trackId: 'philo', chapterId: 'ph-etat', difficulty: 3,
    q: 'Weber définit l\'État par :',
    options: ['Le territoire', 'Le monopole de la violence légitime', 'La religion', 'L\'économie'], answer: 1,
    explanation: '« Le monopole de la violence physique légitime » (Le Savant et le Politique, 1919).' },
  { id: 'philo-q25', trackId: 'philo', chapterId: 'ph-temps', difficulty: 4,
    q: 'Bergson distingue :',
    options: ['Temps physique et durée', 'Temps et espace', 'Instant et éternité', 'Présent et passé'], answer: 0,
    explanation: 'Essai sur les données immédiates de la conscience : la durée est qualitative, le temps est spatialisé.' },
]

/* ============================================================
   FRANÇAIS
   ============================================================ */
const FR: Question[] = [
  { id: 'fr-q1', trackId: 'francais', chapterId: 'fr-poesie', difficulty: 2,
    q: 'Un sonnet est un poème de :',
    options: ['10 vers', '14 vers', '16 vers', '20 vers'], answer: 1,
    explanation: '14 vers (2 quatrains + 2 tercets) selon la forme classique.' },
  { id: 'fr-q2', trackId: 'francais', chapterId: 'fr-poesie', difficulty: 3,
    q: 'Les rimes embrassées sont :',
    options: ['ABBA', 'AABB', 'ABAB', 'ABBA / BAAB'], answer: 0,
    explanation: 'Rimes embrassées = ABBA.' },
  { id: 'fr-q3', trackId: 'francais', chapterId: 'fr-roman', difficulty: 3,
    q: 'Le narrateur omniscient :',
    options: ['Est un personnage interne', 'Connaît tout, y compris les pensées', 'Suit un seul personnage', 'Est absent'], answer: 1,
    explanation: 'Le narrateur omniscient a accès à toutes les pensées, tous les lieux.' },
  { id: 'fr-q4', trackId: 'francais', chapterId: 'fr-theatre', difficulty: 3,
    q: 'Les didascalies sont :',
    options: ['Les répliques des personnages', 'Les indications scéniques (jeu, décor, ton)', 'Les chants du chœur', 'Le monologue'], answer: 1,
    explanation: 'Didascalies = indications scéniques (en italique, entre parenthèses).' },
  { id: 'fr-q5', trackId: 'francais', chapterId: 'fr-theatre', difficulty: 2,
    q: 'La stichomythie est :',
    options: ['Un monologue', 'Un échange rapide de répliques courtes', 'Une tirade', 'Une scène d\'exposition'], answer: 1,
    explanation: 'Stichomythie : dialogue haché, répliques très courtes (rythme vif).' },
  { id: 'fr-q6', trackId: 'francais', chapterId: 'fr-idees', difficulty: 2,
    q: 'Un apologue est :',
    options: ['Un texte argumentatif', 'Un récit court à visée morale ou didactique', 'Une autobiographie', 'Une satire'], answer: 1,
    explanation: 'Apologue = petite fable qui illustre une morale (ex. fables de La Fontaine).' },
  { id: 'fr-q7', trackId: 'francais', chapterId: 'fr-methode-ecrit', difficulty: 3,
    q: 'Le plan dialectique en 3 parties :',
    options: ['Thème / Thème / Thème', 'Thèse / Antithèse / Synthèse', 'Introduction / Développement / Conclusion', 'Cause / Effet / Conclusion'], answer: 1,
    explanation: 'Plan dialectique : on expose une thèse, on la conteste, on dépasse.' },
  { id: 'fr-q8', trackId: 'francais', chapterId: 'fr-roman', difficulty: 3,
    q: 'Le schéma narratif classique :',
    options: ['État initial / Élément perturbateur / Péripéties / Résolution / État final', 'Prologue / Épisode / Épilogue', 'Amitié / Amour / Deuil', 'Acte I / Acte II / Acte III'], answer: 0,
    explanation: 'Les 5 étapes canoniques du schéma narratif selon Bremond / Todorov.' },
  { id: 'fr-q9', trackId: 'francais', chapterId: 'fr-methode-oral', difficulty: 2,
    q: 'Durée de l\'exposé à l\'oral du BAC :',
    options: ['5 min', '10 min', '20 min', '30 min'], answer: 1,
    explanation: 'L\'oral de Français dure 20 min : 10 min d\'exposé + 10 min d\'entretien.' },
  { id: 'fr-q10', trackId: 'francais', chapterId: 'fr-methode-ecrit', difficulty: 3,
    q: 'La problématique en dissertation est :',
    options: ['Une affirmation', 'Une question qui articule le sujet', 'Un plan', 'Une citation'], answer: 1,
    explanation: 'La problématique = question ouverte qui articule le sujet et annonce le mouvement du plan.' },
  { id: 'fr-q11', trackId: 'francais', chapterId: 'fr-poesie', difficulty: 3,
    q: 'La métaphore est :',
    options: ['Une comparaison explicite', 'Une comparaison implicite sans outil comparatif', 'Une personnification', 'Une antithèse'], answer: 1,
    explanation: 'Métaphore : figure d\'analogie sans « comme », « tel que ». (ex. « il est un lion »).' },
  { id: 'fr-q12', trackId: 'francais', chapterId: 'fr-theatre', difficulty: 4,
    q: 'L\'aparté est :',
    options: ['Une tirade', 'Une réplique que le personnage dit au public sans que les autres entendent', 'Un monologue', 'Un dialogue'], answer: 1,
    explanation: 'L\'aparté brise l\'illusion théâtrale : le personnage parle seul au public.' },
]

/* ============================================================
   HISTOIRE-GÉOGRAPHIE
   ============================================================ */
const HI: Question[] = [
  { id: 'hi-q1', trackId: 'histoire', chapterId: 'hi-guerre-froide', difficulty: 2,
    q: 'En quelle année le mur de Berlin est-il tombé ?',
    options: ['1985', '1989', '1991', '1993'], answer: 1,
    explanation: '9 novembre 1989 : chute du mur de Berlin, symbole de la fin de la Guerre froide.' },
  { id: 'hi-q2', trackId: 'histoire', chapterId: 'hi-guerre-froide', difficulty: 3,
    q: 'Quelle est la doctrine soviétique sous Brejnev ?',
    options: ['Coexistence pacifique', 'Doctrine Brejnev (limited sovereignty)', 'Détente', 'Rollback'], answer: 1,
    explanation: 'Doctrine Brejnev (1968) : tout pays socialiste reste sous contrôle soviétique.' },
  { id: 'hi-q3', trackId: 'histoire', chapterId: 'hi-decolonisation', difficulty: 3,
    q: 'Quelle est la date des Accords d\'Évian (fin de la guerre d\'Algérie) ?',
    options: ['1958', '1962', '1968', '1954'], answer: 1,
    explanation: '18 mars 1962 : cessez-le-feu suite aux Accords d\'Évian.' },
  { id: 'hi-q4', trackId: 'histoire', chapterId: 'hi-decolonisation', difficulty: 3,
    q: 'La Conférence de Bandung (1955) marque :',
    options: ['Le début de la Guerre froide', 'L\'émergence du tiers-monde', 'La fin de la décolonisation', 'La création de l\'ONU'], answer: 1,
    explanation: 'Bandung 1955 : 29 pays afro-asiatiques affirment le non-alignement.' },
  { id: 'hi-q5', trackId: 'histoire', chapterId: 'hi-monde-bipolaire', difficulty: 2,
    q: 'L\'URSS est dissoute en :',
    options: ['1989', '1990', '1991', '1992'], answer: 2,
    explanation: '25 décembre 1991 : Gorbatchev démissionne, dissolution de l\'URSS.' },
  { id: 'hi-q6', trackId: 'histoire', chapterId: 'geo-france', difficulty: 3,
    q: 'La métropolisation désigne :',
    options: ['L\'exode rural', 'La concentration des populations dans les grandes agglomérations', 'La déforestation', 'Le tourisme'], answer: 1,
    explanation: 'Métropolisation : croissance des grandes villes en emplois, en population.' },
  { id: 'hi-q7', trackId: 'histoire', chapterId: 'geo-france', difficulty: 3,
    q: 'La périurbanisation se caractérise par :',
    options: ['Le départ des villes vers les banlieues et couronnes périurbaines', 'La fermeture des campagnes', 'L\'urbanisation du centre', 'La construction de tours'], answer: 0,
    explanation: 'Périurbanisation : croissance des communes autour des villes (mobilité pendulaire).' },
  { id: 'hi-q8', trackId: 'histoire', chapterId: 'geo-monde', difficulty: 3,
    q: 'L\'IDH mesure :',
    options: ['Le PIB', 'Le développement humain (santé, éducation, niveau de vie)', 'Les inégalités', 'La démographie'], answer: 1,
    explanation: 'IDH = 0-1 : santé (espérance de vie), éducation (scolarisation), niveau de vie (PIB/h).' },
  { id: 'hi-q9', trackId: 'histoire', chapterId: 'geo-environnement', difficulty: 2,
    q: 'L\'objectif de l\'Accord de Paris (2015) :',
    options: ['Augmenter le PIB', 'Limiter le réchauffement à 1.5°C - 2°C', 'Construire des barrages', 'Aucune'], answer: 1,
    explanation: 'COP21 : limiter le réchauffement climatique bien en-dessous de 2°C, poursuivre 1.5°C.' },
  { id: 'hi-q10', trackId: 'histoire', chapterId: 'geo-monde', difficulty: 3,
    q: 'Le PIB mesure :',
    options: ['La richesse produite sur un territoire pendant 1 an', 'Le bien-être', 'Le développement humain', 'Les inégalités'], answer: 0,
    explanation: 'PIB = somme des valeurs ajoutées produites sur un territoire en un an.' },
]

/* ============================================================
   SES
   ============================================================ */
const SES_Q: Question[] = [
  { id: 'ses-q1', trackId: 'ses', chapterId: 'ses-croissance', difficulty: 2,
    q: 'Le PIB est :',
    options: ['Un indicateur de bien-être', 'Un indicateur de richesse produite', 'Un indicateur d\'inégalités', 'Un taux de chômage'], answer: 1,
    explanation: 'PIB mesure la production marchande. Ce n\'est PAS un indicateur de bien-être.' },
  { id: 'ses-q2', trackId: 'ses', chapterId: 'ses-chomage', difficulty: 3,
    q: 'Le taux de chômage au sens du BIT inclut :',
    options: ['Tous les sans-emploi', 'Les personnes sans emploi, disponibles, en recherche active', 'Les précaires', 'Les inactifs'], answer: 1,
    explanation: 'Définition BIT : sans emploi, disponibles, en recherche active (15-64 ans).' },
  { id: 'ses-q3', trackId: 'ses', chapterId: 'ses-inegalites', difficulty: 4,
    q: 'L\'indice de Gini :',
    options: ['Varie entre 0 et 1, 0 = égalité parfaite', 'Varie entre -1 et 1', 'Mesure le PIB par habitant', 'N\'a pas d\'unité'], answer: 0,
    explanation: 'Gini ∈ [0, 1]. 0 = égalité parfaite, 1 = inégalité totale.' },
  { id: 'ses-q4', trackId: 'ses', chapterId: 'ses-sociologie', difficulty: 3,
    q: 'Bourdieu appelle « habitus » :',
    options: ['Une action rationnelle', 'Un système de dispositions acquises socialement', 'Un réseau social', 'Une classe'], answer: 1,
    explanation: 'Habitus : dispositions durables, structurées par les conditions sociales.' },
  { id: 'ses-q5', trackId: 'ses', chapterId: 'ses-sources', difficulty: 4,
    q: 'La croissance endogène met en avant :',
    options: ['L\'accumulation du capital physique', 'Le progrès technique et le capital humain', 'L\'épuisement des ressources', 'Le commerce international'], answer: 1,
    explanation: 'Croissance endogène (Romer, Lucas) : innovation, capital humain, institutions.' },
  { id: 'ses-q6', trackId: 'ses', chapterId: 'ses-mondialisation', difficulty: 2,
    q: 'Les IDE sont :',
    options: ['Investissements directs étrangers', 'Importations domestiques extérieures', 'Aides au développement', 'Aucune'], answer: 0,
    explanation: 'IDE = Investissements Directs Étrangers (prise de contrôle >10%).' },
  { id: 'ses-q7', trackId: 'ses', chapterId: 'ses-stratification', difficulty: 3,
    q: 'La PCS de l\'INSEE classe :',
    options: ['Les salaires', 'Les catégories socioprofessionnelles', 'Les diplômes', 'Les régions'], answer: 1,
    explanation: 'PCS = Professions et Catégories Socioprofessionnelles (cadres, employés, ouvriers...).' },
  { id: 'ses-q8', trackId: 'ses', chapterId: 'ses-action-publique', difficulty: 4,
    q: 'Une externalité négative est :',
    options: ['Un bénéfice pour un tiers', 'Un coût supporté par un tiers non impliqué dans la décision', 'Un marché efficace', 'Une taxe'], answer: 1,
    explanation: 'Externalité = effet sur un tiers. Négative = coût (pollution, tabagisme passif).' },
  { id: 'ses-q9', trackId: 'ses', chapterId: 'ses-politique', difficulty: 3,
    q: 'Un sondage politique est :',
    options: ['Une preuve absolue', 'Un outil de mesure soumis à des biais', 'Une obligation de vote', 'Un sondage scientifique parfait'], answer: 1,
    explanation: 'Sondages : marges d\'erreur, biais d\'échantillonnage, formulation des questions.' },
  { id: 'ses-q10', trackId: 'ses', chapterId: 'ses-eco-politique', difficulty: 4,
    q: 'La BCE (Banque Centrale Européenne) contrôle :',
    options: ['La politique budgétaire', 'La politique monétaire (taux d\'intérêt directeur)', 'La politique commerciale', 'Le budget de l\'État'], answer: 1,
    explanation: 'BCE = politique monétaire. États = politique budgétaire (dépenses, impôts).' },
]

/* ============================================================
   NSI
   ============================================================ */
const NS: Question[] = [
  { id: 'nsi-q1', trackId: 'nsi', chapterId: 'ns-recursivite', difficulty: 2,
    q: 'Que fait ce code Python ?\n```\ndef f(n):\n  if n == 0: return 0\n  return f(n-1) + n\n```',
    options: ['Factorielle de n', 'Somme des entiers de 0 à n', 'Le produit des entiers', 'Une boucle infinie'], answer: 1,
    explanation: 'f(n) = n + (n-1) + ... + 0 = n(n+1)/2. Si on commence à f(0)=0.' },
  { id: 'nsi-q2', trackId: 'nsi', chapterId: 'ns-structures', difficulty: 2,
    q: 'Une pile (LIFO) :',
    options: ['Ajoute et retire des deux bouts', 'Ajoute au sommet et retire au sommet', 'Ajoute au sommet et retire à la base', 'Aucune des réponses'], answer: 1,
    explanation: 'Pile = Last In First Out. push au sommet, pop au sommet.' },
  { id: 'nsi-q3', trackId: 'nsi', chapterId: 'ns-tris', difficulty: 3,
    q: 'Complexité du tri par insertion dans le pire cas :',
    options: ['O(n)', 'O(log n)', 'O(n²)', 'O(n log n)'], answer: 2,
    explanation: 'Tri par insertion : O(n) meilleur cas, O(n²) pire cas (liste inversée).' },
  { id: 'nsi-q4', trackId: 'nsi', chapterId: 'ns-sql', difficulty: 3,
    q: 'Requête SQL pour obtenir tous les élèves d\'une classe :',
    options: ['SELECT * FROM eleves WHERE classe = \'Terminal\'', 'SELECT eleves WHERE classe = \'Terminal\'', 'FIND eleves WHERE classe', 'EXTRACT eleves FOR Terminal'], answer: 0,
    explanation: 'SELECT * FROM table WHERE condition : syntaxe SQL standard.' },
  { id: 'nsi-q5', trackId: 'nsi', chapterId: 'ns-sql', difficulty: 3,
    q: 'Que retourne `SELECT COUNT(*) FROM films` ?',
    options: ['Le premier film', 'La liste des films', 'Le nombre de lignes', 'Une erreur'], answer: 2,
    explanation: 'COUNT(*) retourne le nombre de lignes.' },
  { id: 'nsi-q6', trackId: 'nsi', chapterId: 'ns-dpr', difficulty: 3,
    q: 'Complexité de la recherche dichotomique :',
    options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], answer: 1,
    explanation: 'Dichotomie : on divise par 2 à chaque étape → O(log n).' },
  { id: 'nsi-q7', trackId: 'nsi', chapterId: 'ns-graphes', difficulty: 3,
    q: 'BFS explore un graphe :',
    options: ['En profondeur', 'En largeur d\'abord (par niveau)', 'Au hasard', 'Selon Dijkstra'], answer: 1,
    explanation: 'BFS = Breadth-First Search : explore tous les voisins d\'un nœud avant de descendre.' },
  { id: 'nsi-q8', trackId: 'nsi', chapterId: 'ns-archi', difficulty: 4,
    q: 'Le CPU exécute :',
    options: ['Les programmes en Python', 'Le code machine (binaire)', 'Le HTML', 'Les bases de données'], answer: 1,
    explanation: 'CPU exécute les instructions machine en binaire.' },
  { id: 'nsi-q9', trackId: 'nsi', chapterId: 'ns-reseaux', difficulty: 3,
    q: 'Le protocole HTTP :',
    options: ['Chiffre les communications', 'Sert des pages web (80 par défaut)', 'Gère les emails', 'Synchronise les horloges'], answer: 1,
    explanation: 'HTTP : protocole web, port 80 (HTTPS = 443).' },
  { id: 'nsi-q10', trackId: 'nsi', chapterId: 'ns-reseaux', difficulty: 3,
    q: 'Une adresse IP v4 fait :',
    options: ['16 bits', '32 bits (4 octets)', '64 bits', '128 bits'], answer: 1,
    explanation: 'IPv4 = 32 bits (ex. 192.168.1.1). IPv6 = 128 bits.' },
  { id: 'nsi-q11', trackId: 'nsi', chapterId: 'ns-secu', difficulty: 3,
    q: 'Le chiffrement asymétrique utilise :',
    options: ['Une clé unique', 'Une paire de clés (publique + privée)', 'Deux clés identiques', 'Aucun'], answer: 1,
    explanation: 'RSA : clé publique pour chiffrer, clé privée pour déchiffrer.' },
  { id: 'nsi-q12', trackId: 'nsi', chapterId: 'ns-arbres', difficulty: 4,
    q: 'Un arbre binaire de recherche (ABR) :',
    options: ['N\'a aucune structure', 'Pour chaque nœud, fils gauche < nœud < fils droit', 'A toujours 2 fils', 'Est une liste'], answer: 1,
    explanation: 'ABR : propriété d\'ordre (gauche ≤ nœud ≤ droit) → recherche en O(h).' },
  { id: 'nsi-q13', trackId: 'nsi', chapterId: 'ns-binaire', difficulty: 3,
    q: 'Combien de bits dans 0101 1100 ?',
    options: ['4', '8', '16', '32'], answer: 1,
    explanation: '8 bits (un octet).' },
  { id: 'nsi-q14', trackId: 'nsi', chapterId: 'ns-binaire', difficulty: 3,
    q: 'En hexadécimal, FF vaut en décimal :',
    options: ['127', '255', '256', '1023'], answer: 1,
    explanation: 'FF_16 = 15·16 + 15 = 255.' },
  { id: 'nsi-q15', trackId: 'nsi', chapterId: 'ns-dynamique', difficulty: 4,
    q: 'Mémoïser Fibonacci permet :',
    options: ['De réduire la complexité de O(2^n) à O(n)', 'D\'augmenter la mémoire', 'De rien', 'De rendre récursif'], answer: 0,
    explanation: 'Sans mémoïsation : O(2^n). Avec : O(n) (programmation dynamique).' },
  { id: 'nsi-q16', trackId: 'nsi', chapterId: 'ns-bool', difficulty: 3,
    q: 'La fonction XOR :',
    options: ['Renvoie 1 si les deux bits sont identiques', 'Renvoie 1 si exactement un bit est 1', 'Renvoie toujours 0', 'Renvoie toujours 1'], answer: 1,
    explanation: 'XOR (⊕) : 1 si bits différents.' },
  { id: 'nsi-q17', trackId: 'nsi', chapterId: 'ns-web', difficulty: 3,
    q: 'HTML est un langage de :',
    options: ['Programmation', 'Description / structuration', 'Style', 'Script'], answer: 1,
    explanation: 'HTML = HyperText Markup Language : description / structuration. CSS = style. JS = script.' },
  { id: 'nsi-q18', trackId: 'nsi', chapterId: 'ns-os', difficulty: 4,
    q: 'Un thread partage avec les autres threads :',
    options: ['Sa mémoire', 'Son espace d\'adressage', 'Ses registres', 'Son PID'], answer: 1,
    explanation: 'Threads d\'un même processus partagent l\'espace d\'adressage. Les processus ont chacun leur mémoire.' },
]

/* ============================================================
   Catalogue complet
   ============================================================ */
export const ALL_QUESTIONS: Question[] = [...MA, ...PH, ...SV, ...PHI, ...FR, ...HI, ...SES_Q, ...NS]

export function questionsByTrack(trackId: TrackId): Question[] {
  return ALL_QUESTIONS.filter((q) => q.trackId === trackId)
}

export function questionsByChapter(trackId: TrackId, chapterId: string): Question[] {
  return ALL_QUESTIONS.filter((q) => q.trackId === trackId && q.chapterId === chapterId)
}

export function shuffleQuestions(questions: Question[], seed: number): Question[] {
  // Deterministic shuffle (LCG)
  const arr = [...questions]
  let s = seed
  for (let i = arr.length - 1; i > 0; i--) {
    s = (s * 9301 + 49297) % 233280
    const j = s % (i + 1)
    ;[arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr
}

export function questionById(id: string): Question | undefined {
  return ALL_QUESTIONS.find((q) => q.id === id)
}